In [1]:
import numpy as np

a=np.random.randn(5)

In [2]:
print(a)

[-1.03939835  0.85757789  1.57610658  1.00454786  0.57903778]


In [3]:
print(a.shape)

(5,)


In [4]:
print(a.T)

[-1.03939835  0.85757789  1.57610658  1.00454786  0.57903778]


In [5]:
print(np.dot(a,a.T))

5.644301855256021


In [6]:
a=np.random.randn(5,1)
print(a)

[[-0.50180581]
 [ 0.11516398]
 [ 1.30670149]
 [-0.55493142]
 [ 1.61350903]]


In [7]:
print(a.T)

[[-0.50180581  0.11516398  1.30670149 -0.55493142  1.61350903]]


In [8]:
print(a.shape)

(5, 1)


In [9]:
print(np.dot(a,a.T))

[[ 0.25180907 -0.05778995 -0.6557104   0.27846781 -0.80966821]
 [-0.05778995  0.01326274  0.15048494 -0.06390811  0.18581812]
 [-0.6557104   0.15048494  1.70746878 -0.72512971  2.10837465]
 [ 0.27846781 -0.06390811 -0.72512971  0.30794888 -0.89538686]
 [-0.80966821  0.18581812  2.10837465 -0.89538686  2.6034114 ]]


In [10]:
a=np.random.randn(2,3)
b=np.random.randn(2,1)
c=a+b
print(c.shape)

(2, 3)


In [26]:
a=np.random.randn(3,3)
b=np.random.randn(3,1)
c=a*b
print(c.shape)

(3, 3)


In [12]:
a=np.random.randn(12288,150)
b=np.random.randn(150,45)
c=np.dot(a,b)
print(c.shape)

(12288, 45)


In [24]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
for i in range(3):
    for j in range(4):
        c[i][j]=a[i][j]+b[j]
print(c)

#c=a.T+b.T
#print(c)

IndexError: index 3 is out of bounds for axis 0 with size 3

In [25]:
a=np.random.randn(3,4)
b=np.random.randn(4,1)
for i in range(3):
    for j in range(4):
        c[i][j]=a[i][j]+b[j]
print(c)

#c=a.T+b.T
#print(c)

IndexError: index 3 is out of bounds for axis 0 with size 3